# Generated by Django 5.0.1 on 2024-01-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('part_title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='static/images/About')),
                ('job_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('website', models.URLField()),
                ('phone_code', models.CharField(choices=[('Uzb ', '+998'), ('Usa', '+1'), ('Ru', '+7'), ('Eng', '+44'), ('Fr', '+33'), ('Ca', '+1')], max_length=55)),
                ('phone_number', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'About',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('part_title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/fact')),
                ('count', models.IntegerField()),
                ('short_text', models.CharField(max_length=255)),
            ],
        ),
    ]
