# Generated by Django 5.0.1 on 2024-01-22 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_decs', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('phone_code', models.CharField(max_length=55)),
                ('phone_number', models.CharField(max_length=55)),
                ('city_name', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('No degree', 'No degree'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ("Doctor's", "Doctor's")], max_length=255)),
                ('email_field', models.EmailField(max_length=254)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Freelance', 'Freelance'), ('Remote', 'Remote'), ('Other', 'Other')], max_length=255)),
                ('about_job', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=255)),
                ('my_second_name', models.CharField(max_length=255)),
                ('my_age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
                ('my_birthday', models.DateField()),
                ('about_avatar_img', models.ImageField(upload_to='static/images/static_images/about_avatar_img')),
                ('background_img', models.ImageField(upload_to='static/images/static_images/background_img')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('call', models.CharField(max_length=200)),
                ('location_coordinate', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Me',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_cont', models.IntegerField()),
                ('fact_short_text', models.CharField(max_length=255)),
                ('fact_logo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Fact',
                'verbose_name_plural': 'Facts',
            },
        ),
        migrations.CreateModel(
            name='LeftSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_side_name', models.CharField(max_length=55)),
                ('left_side_img', models.ImageField(upload_to='static/images/static_images/left_side_images/')),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('skype_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Static',
                'verbose_name_plural': 'Statics',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=55, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='static/images/portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_desc', models.CharField(max_length=255)),
                ('service_logo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=55)),
                ('skill_percent', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.CharField(max_length=255)),
                ('user_img', models.ImageField(upload_to='static/images/testimonials')),
                ('user_name', models.CharField(max_length=55)),
                ('user_second_name', models.CharField(max_length=55)),
                ('user_job_name', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
