# Generated by Django 5.0.1 on 2024-01-26 08:23

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField()),
                ('degree', models.CharField(blank=True, choices=[('No degree', 'No degree'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ("Doctor's", "Doctor's")], max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Freelance', 'Freelance'), ('Remote', 'Remote'), ('Other', 'Other')], max_length=255, null=True)),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Model',
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
                ('birthday', models.DateField()),
                ('about_part_img', models.ImageField(upload_to='static/images/info_models/about_me')),
                ('background_img', models.ImageField(upload_to='static/images/info_models/about_me')),
            ],
            options={
                'verbose_name_plural': 'About Me INFO',
            },
        ),
        migrations.CreateModel(
            name='AboutPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Static Part',
            },
        ),
        migrations.CreateModel(
            name='CategoryPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=55, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Category',
            },
        ),
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=55)),
                ('phone_number', models.CharField(max_length=200)),
                ('location_coordinate', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Contact Me INFO',
            },
        ),
        migrations.CreateModel(
            name='ContactPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Static Part',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.DateTimeField()),
                ('end_year', models.DateTimeField(auto_now=True, null=True)),
                ('place_name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('start_year', models.DateTimeField(blank=True, null=True)),
                ('end_year', models.DateTimeField(auto_now=True, null=True)),
                ('place_name', models.CharField(blank=True, max_length=55, null=True)),
                ('experience_desc', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_count', models.IntegerField(blank=True, null=True)),
                ('fact_short_text', models.CharField(blank=True, max_length=255, null=True)),
                ('fact_logo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fact Model',
            },
        ),
        migrations.CreateModel(
            name='FactPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fact Static Part',
            },
        ),
        migrations.CreateModel(
            name='LeftSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_side_my_img', models.ImageField(upload_to='static/images/info_models/left_block_images/')),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('skype_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Left Side INFO',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Static Part',
            },
        ),
        migrations.CreateModel(
            name='ResumeBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=55, null=True)),
                ('education', models.CharField(blank=True, max_length=55, null=True)),
                ('experience', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'verbose_name_plural': 'Resume Block Static Parts',
            },
        ),
        migrations.CreateModel(
            name='ResumePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Resume Static Part',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Model',
            },
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Static Part',
            },
        ),
        migrations.CreateModel(
            name='SkillPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Static Part',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Model',
            },
        ),
        migrations.CreateModel(
            name='TestimonialPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonial Static Part',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='static/images/testimonials')),
                ('user_name', models.CharField(blank=True, max_length=55, null=True)),
                ('user_second_name', models.CharField(blank=True, max_length=55, null=True)),
                ('user_job_name', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonial Model',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/images/portfolio/<django.db.models.fields.CharField>/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_app.categoryportfolio')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Model',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('client', models.CharField(blank=True, max_length=55, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_app.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/project_detail_images/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='cv_app.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=55)),
                ('desc', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_email', to='cv_app.contactme')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_name', to='cv_app.aboutme')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_number', to='cv_app.contactme')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_place', to='cv_app.contactme')),
            ],
            options={
                'verbose_name_plural': 'Summary',
            },
        ),
    ]
