# Generated by Django 5.0.1 on 2024-01-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryportfolio',
            options={'verbose_name_plural': 'Portfolio Category'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_category',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_app.categoryportfolio'),
        ),
    ]
