# Generated by Django 5.0.1 on 2024-01-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leftside',
            options={'verbose_name_plural': 'Left Side'},
        ),
        migrations.RenameField(
            model_name='leftside',
            old_name='left_side_img',
            new_name='left_side_my_img',
        ),
    ]
