# Generated by Django 5.0.1 on 2024-01-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticobjects',
            options={'verbose_name': 'Static', 'verbose_name_plural': 'Statics'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='my_name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='my_second_name',
        ),
    ]
