# Generated by Django 5.0.1 on 2024-01-20 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'verbose_name': 'Fact'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='job_title',
            new_name='about_job',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='about',
            name='degree',
            field=models.CharField(choices=[("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ("Doctor's", "Doctor's")], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='email_field',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='job_about',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Freelance', 'Freelance'), ('Remote', 'Remote'), ('Other', 'Other')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(upload_to='static/images/about'),
        ),
    ]
