# Generated by Django 5.0.1 on 2024-01-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
