# Generated by Django 5.0.1 on 2024-01-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_alter_categoryportfolio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='cv_app.categoryportfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
