# Generated by Django 5.0.1 on 2024-01-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_alter_experience_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
