# Generated by Django 5.0.1 on 2024-01-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0003_alter_contact_options_contact_email_contact_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
