# Generated by Django 5.0.1 on 2024-01-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0004_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticobjects',
            name='background_img',
            field=models.ImageField(default=1, upload_to='static/images/static_images'),
            preserve_default=False,
        ),
    ]
