# Generated by Django 5.0.1 on 2024-01-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0006_alter_summary_desc_alter_summary_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='about_part_img',
            field=models.ImageField(upload_to='static/images/info_models/about_me/avatar_photo/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='background_img',
            field=models.ImageField(upload_to='static/images/info_models/about_me/background_photo/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(upload_to='images/project_detail_images/'),
        ),
    ]
