# Generated by Django 5.0.1 on 2024-01-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0007_alter_aboutme_about_part_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimages',
            name='project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(related_name='project_images', to='cv_app.projectimages'),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/project_detail_images/'),
        ),
    ]
