# Generated by Django 5.0.1 on 2024-01-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0009_projectimages_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryportfolio',
            options={'verbose_name_plural': 'Portfolio Category Model'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education Model'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name_plural': 'Experience Model'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Project Model'},
        ),
        migrations.AlterModelOptions(
            name='projectimages',
            options={'verbose_name_plural': 'Project Images Model'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'Summary Model'},
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
