# Generated by Django 5.0.1 on 2024-01-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0010_alter_categoryportfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/project_detail_images/'),
        ),
    ]
