# Generated by Django 5.0.1 on 2024-01-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0012_remove_project_images_projectimages_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
