# Generated by Django 5.0.1 on 2024-01-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0014_rename_portfolio_projectimages_img_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimages',
            old_name='img_portfolio',
            new_name='slug',
        ),
    ]
