# Generated by Django 5.0.1 on 2024-01-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0015_rename_img_portfolio_projectimages_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Project Detail_Page Model'},
        ),
    ]
