# Generated by Django 5.0.1 on 2024-01-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0016_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Project Detail Model'},
        ),
    ]
