# Generated by Django 5.0.1 on 2024-01-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0020_portfolio_level_portfolio_lft_portfolio_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='level',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='tree_id',
        ),
    ]
