# Generated by Django 5.0.1 on 2024-01-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0021_remove_portfolio_level_remove_portfolio_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='parent',
        ),
    ]
