# Generated by Django 5.0.1 on 2024-01-30 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0022_remove_portfolio_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='about_part_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/info_models/about_me/avatar_photo/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='background_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/info_models/about_me/background_photo/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='city',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='country_code',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
