# Generated by Django 5.0.1 on 2024-01-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0023_alter_aboutme_about_part_img_alter_aboutme_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='GetContactMessage',
        ),
    ]
