# Generated by Django 5.0.1 on 2024-01-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0025_alter_getcontactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='detail_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
